### ISSUE TITLE
[HELP] How does this exactly work? How can I access services behind VPN? 

### ISSUE THREAD

**Issue by goliath888** [tprasadtp/protonvpn-docker#105]
I just deployed the example docker-compose file in my server and I want to access to pyload from my computer (in the same lan network) but I cannot access.

I can see in logs that "VPN is running and healthy" and pyload too. 

I think that my problem is that I am missing something or do not undernstand how does work. I try to access to pyload with <MY-SERVER-IP:8000> or something like that but nothing seems to work. 

If I ssh into my server and try the same thing, I get the same result. Only If I login into docker console, then I can see that pyload is running and accesible, but only inside the docker container. How can I access from the outside?

**Comment by Ruvon** [comment]
I got it to work for myself by changing the docker-compose

    expose:
      - XXXX

to

    ports:
      - XXXX:XXXX

I'm not quite sure why the template uses expose instead of ports, since expose only allows the ports to be accessed from within the docker network, but not for the outside AFAIK

if you change the part of the docker-compose.yaml file it should afterwards be accessible under YOUR.HOST.IP.ADDRESS:XXXX which could look something like 192.168.0.2:8000

**Comment by goliath888** [comment]
Ok, that worked, partially. 

I only can access the service if vpn is not connected (for example, bad login credentials). As soon as VPN is running and healthy, then I cannot access. 

This is a sample docker-compose I am using for testing:

```
version: '3.4'
services:
  protonvpn:
    container_name: protonvpn
    environment:
      # Credentials
      PROTONVPN_USERNAME: XXXXXXXX
      PROTONVPN_PASSWORD: XXXXXXXX
      # Override these where applicable
      PROTONVPN_SERVER: NL
      PROTONVPN_TIER: 0
    # Always use semver tags, avoid using tag latest!
    image: ghcr.io/tprasadtp/protonvpn:latest
    restart: unless-stopped
    networks:
      - internet
      - proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # Expose pyload container's port here!
    ports:
      - 6767:6767


  bazarr:
    depends_on:
      - protonvpn
    container_name: bazarr
    image: linuxserver/bazarr:latest
    userns_mode: host
    network_mode: service:protonvpn
    
  bazarr2:
    depends_on:
      - protonvpn
    container_name: bazarr2
    image: linuxserver/bazarr:latest
    userns_mode: host
    network_mode: bridge
    ports:
      - 6768:6767
    
    

networks:
  internet:
  proxy:
    internal: true

```

SERVER-IP:6768 it is always running, it is ok.

SERVER-IP:6767 only works if VPN is not connected. If it connects, the that url becames inaccessible.
