### ISSUE TITLE
2.2.6 Gateway Timeout

### ISSUE THREAD

**Issue by hadim** [tprasadtp/protonvpn-docker#11]
I run into a Gateway Timeout error using the newly released 2.2.6. Reverting back to `2.2.2-hotfix-4` works as before.

```bash
$ dc version
docker-compose version 1.28.0-rc3, build unknown
docker-py version: 4.4.1
CPython version: 3.8.6
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

```yaml
  # Torrent Downloader Server
  qbittorrent:
    container_name: qbittorrent
    # Waiting fix at https://github.com/qbittorrent/qBittorrent/issues/13389
    image: linuxserver/qbittorrent:version-14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1
    volumes:
      - /home/xxx/xxxx/qBittorrent:/config
      - freda_Multimedia_Download:/downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=EST
      - UMASK_SET=022
      - WEBUI_PORT=8787
    restart: unless-stopped
    network_mode: service:qbittorrent-vpn
    depends_on:
      - qbittorrent-vpn

  # Companion VPN container for qbittorrent
  # When restart the vpn container you must also delete and restart the parent's one:
  # `dc rm -fs qbittorrent qbittorrent-vpn && dc up -d`
  qbittorrent-vpn:
    image: ghcr.io/tprasadtp/protonvpn:latest
    # image: tprasadtp/protonvpn:2.2.2-hotfix-4
    container_name: qbittorrent-vpn
    environment:
      - PROTONVPN_USERNAME=xxx
      - PROTONVPN_PASSWORD=xxxxx
      - PROTONVPN_TIER=2
      - PROTONVPN_PROTOCOL=udp
      - PROTONVPN_COUNTRY=CA
      - PROTONVPN_DNS_LEAK_PROTECT=0
      - NETWORK=192.168.1.0
      - DEBUG=1
    cap_add:
      - NET_ADMIN
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8787:8787
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.3
      - 1.0.0.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`xxx.xxx.xxxx.org`)"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=mydnschallenge"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8787"
```

logs:

```bash
qbittorrent-vpn    | [services.d] starting services
qbittorrent-vpn    | [Service - INIT] Daemon check interval is set to #60
qbittorrent-vpn    | [Service - INIT] Reconnect treshold is #3
qbittorrent-vpn    | [Service - INIT] checking orphaned openvpn process
qbittorrent-vpn    | [services.d] done.
qbittorrent-vpn    | [Service - INIT] This appears to be a fresh start!
qbittorrent-vpn    | [Service - CONN] Using Fastest Server from CA
qbittorrent-vpn    | 2021-01-13 11:49:17,902 — protonvpn-cli — DEBUG — cli:84 — ###########################
qbittorrent-vpn    | 2021-01-13 11:49:17,903 — protonvpn-cli — DEBUG — cli:85 — ### NEW PROCESS STARTED ###
qbittorrent-vpn    | 2021-01-13 11:49:17,903 — protonvpn-cli — DEBUG — cli:86 — ###########################
qbittorrent-vpn    | 2021-01-13 11:49:17,903 — protonvpn-cli — DEBUG — cli:87 — ['/usr/local/bin/protonvpn', 'connect', '--cc', 'CA']
qbittorrent-vpn    | 2021-01-13 11:49:17,904 — protonvpn-cli — DEBUG — cli:88 — USER: root
qbittorrent-vpn    | 2021-01-13 11:49:17,904 — protonvpn-cli — DEBUG — cli:89 — CONFIG_DIR: /root/.pvpn-cli
qbittorrent-vpn    | 2021-01-13 11:49:17,910 — protonvpn-cli — DEBUG — cli:92 — Arguments
qbittorrent-vpn    | {'--cc': 'CA', '--fastest': False, '--help': False, '--p2p': False, '--random': False, '--sc': False, '--tor': False, '--version': False, '-p': None, '<servername>': None, 'c': False, 'configure': False, 'connect': True, 'd': False, 'disconnect': False, 'examples': False, 'init': False, 'r': False, 'reconnect': False, 'refresh': False, 's': False, 'status': False}
qbittorrent-vpn    | 2021-01-13 11:49:17,930 — protonvpn-cli — DEBUG — country_f:170 — Starting fastest country connect
qbittorrent-vpn    | 2021-01-13 11:49:17,931 — protonvpn-cli — DEBUG — disconnect:307 — Initiating disconnect
qbittorrent-vpn    | 2021-01-13 11:49:17,936 — protonvpn-cli — DEBUG — is_connected:195 — Checking connection Status. OpenVPN processes: 0
qbittorrent-vpn    | 2021-01-13 11:49:17,937 — protonvpn-cli — DEBUG — manage_dns:608 — Restoring DNS
qbittorrent-vpn    | 2021-01-13 11:49:17,937 — protonvpn-cli — DEBUG — manage_dns:625 — No Backupfile found
qbittorrent-vpn    | 2021-01-13 11:49:17,937 — protonvpn-cli — DEBUG — manage_ipv6:688 — Restoring ip6tables
qbittorrent-vpn    | 2021-01-13 11:49:17,937 — protonvpn-cli — DEBUG — manage_ipv6:703 — No Backupfile found
qbittorrent-vpn    | 2021-01-13 11:49:17,938 — protonvpn-cli — DEBUG — manage_killswitch:778 — Restoring iptables
qbittorrent-vpn    | 2021-01-13 11:49:17,938 — protonvpn-cli — DEBUG — manage_killswitch:787 — No Backupfile found
qbittorrent-vpn    | 2021-01-13 11:49:17,938 — protonvpn-cli — DEBUG — disconnect:347 — No connection found
qbittorrent-vpn    | 2021-01-13 11:49:17,939 — protonvpn-cli — DEBUG — call_api:36 — Initiating API Call: https://api.protonvpn.ch/vpn/logicals
qbittorrent-vpn    | 2021-01-13 11:49:18,893 — protonvpn-cli — DEBUG — call_api:65 — Successful json response
qbittorrent-vpn    | 2021-01-13 11:49:18,970 — protonvpn-cli — DEBUG — pull_server_data:87 — SERVER_INFO_FILE written
qbittorrent-vpn    | 2021-01-13 11:49:18,980 — protonvpn-cli — DEBUG — pull_server_data:94 — last_api_call updated
qbittorrent-vpn    | 2021-01-13 11:49:18,985 — protonvpn-cli — DEBUG — get_servers:101 — Reading servers from file
qbittorrent-vpn    | 2021-01-13 11:49:18,998 — protonvpn-cli — DEBUG — get_fastest_server:170 — Returning fastest server with pool size 1
qbittorrent-vpn    | 2021-01-13 11:49:18,998 — protonvpn-cli — DEBUG — openvpn_connect:442 — Initiating OpenVPN connection
qbittorrent-vpn    | 2021-01-13 11:49:18,998 — protonvpn-cli — DEBUG — openvpn_connect:443 — Connecting to CA#18 via UDP
qbittorrent-vpn    | 2021-01-13 11:49:18,999 — protonvpn-cli — DEBUG — get_servers:101 — Reading servers from file
qbittorrent-vpn    | 2021-01-13 11:49:19,023 — protonvpn-cli — DEBUG — render_j2_template:255 — Rendered /root/.pvpn-cli/connect.ovpn from openvpn_template.j2
qbittorrent-vpn    | 2021-01-13 11:49:19,033 — protonvpn-cli — DEBUG — disconnect:307 — Initiating disconnect
qbittorrent-vpn    | 2021-01-13 11:49:19,038 — protonvpn-cli — DEBUG — is_connected:195 — Checking connection Status. OpenVPN processes: 0
qbittorrent-vpn    | 2021-01-13 11:49:19,039 — protonvpn-cli — DEBUG — manage_dns:608 — Restoring DNS
qbittorrent-vpn    | 2021-01-13 11:49:19,039 — protonvpn-cli — DEBUG — manage_dns:625 — No Backupfile found
qbittorrent-vpn    | 2021-01-13 11:49:19,039 — protonvpn-cli — DEBUG — manage_ipv6:688 — Restoring ip6tables
qbittorrent-vpn    | 2021-01-13 11:49:19,039 — protonvpn-cli — DEBUG — manage_ipv6:703 — No Backupfile found
qbittorrent-vpn    | 2021-01-13 11:49:19,039 — protonvpn-cli — DEBUG — manage_killswitch:778 — Restoring iptables
qbittorrent-vpn    | 2021-01-13 11:49:19,040 — protonvpn-cli — DEBUG — manage_killswitch:787 — No Backupfile found
qbittorrent-vpn    | 2021-01-13 11:49:19,040 — protonvpn-cli — DEBUG — disconnect:347 — No connection found
qbittorrent-vpn    | 2021-01-13 11:49:19,040 — protonvpn-cli — DEBUG — get_ip_info:143 — Getting IP Information
qbittorrent-vpn    | 2021-01-13 11:49:19,041 — protonvpn-cli — DEBUG — call_api:36 — Initiating API Call: https://api.protonvpn.ch/vpn/location
qbittorrent-vpn    | 2021-01-13 11:49:19,447 — protonvpn-cli — DEBUG — call_api:65 — Successful json response
qbittorrent-vpn    | 2021-01-13 11:49:19,452 — protonvpn-cli — DEBUG — openvpn_connect:476 — OpenVPN process started
qbittorrent-vpn    | 2021-01-13 11:49:20,758 — protonvpn-cli — DEBUG — set_config_value:133 — Writing dns_server to [metadata] in config file
qbittorrent-vpn    | 2021-01-13 11:49:20,759 — protonvpn-cli — DEBUG — manage_dns:556 — Leak Protection initiated
qbittorrent-vpn    | 2021-01-13 11:49:20,760 — protonvpn-cli — DEBUG — manage_dns:564 — DNS Leak Protection is disabled
qbittorrent-vpn    | 2021-01-13 11:49:20,761 — protonvpn-cli — DEBUG — manage_ipv6:645 — Disabling IPv6
qbittorrent-vpn    | 2021-01-13 11:49:20,766 — protonvpn-cli — DEBUG — manage_ipv6:656 — IPv6 is disabled or unavailable, skipping leak protection
qbittorrent-vpn    | 2021-01-13 11:49:20,767 — protonvpn-cli — DEBUG — manage_killswitch:811 — Backing up iptables rules
qbittorrent-vpn    | 2021-01-13 11:49:20,821 — protonvpn-cli — DEBUG — manage_killswitch:862 — Kill Switch enabled
qbittorrent-vpn    | 2021-01-13 11:49:20,822 — protonvpn-cli — DEBUG — get_ip_info:143 — Getting IP Information
qbittorrent-vpn    | 2021-01-13 11:49:20,823 — protonvpn-cli — DEBUG — call_api:36 — Initiating API Call: https://api.protonvpn.ch/vpn/location
qbittorrent-vpn    | 2021-01-13 11:49:21,333 — protonvpn-cli — DEBUG — call_api:65 — Successful json response
qbittorrent-vpn    | 2021-01-13 11:49:21,333 — protonvpn-cli — DEBUG — openvpn_connect:510 — Connection successful
qbittorrent-vpn    | 2021-01-13 11:49:21,333 — protonvpn-cli — DEBUG — openvpn_connect:529 — Writing connection info to file
qbittorrent-vpn    | 2021-01-13 11:49:21,334 — protonvpn-cli — DEBUG — check_update:384 — Checking for new update
qbittorrent-vpn    | 2021-01-13 11:49:21,334 — protonvpn-cli — DEBUG — check_update:387 — Current: [2, 2, 6]
qbittorrent-vpn    | 2021-01-13 11:49:21,335 — protonvpn-cli — DEBUG — get_latest_version:356 — Calling pypi API
qbittorrent-vpn    | 2021-01-13 11:49:21,502 — protonvpn-cli — DEBUG — check_update:395 — Latest: [2, 2, 6]
qbittorrent-vpn    | 2021-01-13 11:49:21,502 — protonvpn-cli — DEBUG — check_update:407 — No update
qbittorrent-vpn    | 2021-01-13 11:49:21,503 — protonvpn-cli — DEBUG — set_config_value:133 — Writing last_update_check to [metadata] in config file
qbittorrent-vpn    | Connecting to CA#18 via UDP...
qbittorrent-vpn    | Connected!
qbittorrent-vpn    | [Service - CHCK] OK!
qbittorrent-vpn    | [Service - CHCK] OK!
```

I also tried without setting the dns.

ping @tprasadtp
