### ISSUE TITLE
Using ProtonVPN-Docker as a 'proxy' docker results in timeouts on ports

### ISSUE THREAD

**Issue by LovelessCodes** [tprasadtp/protonvpn-docker#15]
Trying this configuration on docker-compose, when trying to access the opened ports for the web interface of in this case, sabnzbd, it basically loads forever and timeouts.
```yaml
version: "3.8"
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: service:protonvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /plex:/config
      - /plex/downloads:/downloads
    depends_on:
      - sabnzbd-vpn
    restart: unless-stopped
  protonvpn:
    image: ghcr.io/tprasadtp/protonvpn:latest
    container_name: sabnzbd-vpn
    environment:
      - PROTONVPN_USERNAME=REDACTED
      - PROTONVPN_PASSWORD=REDACTED
      - PROTONVPN_TIER=2
      - PROTONVPN_COUNTRY=NL
      - DEBUG=1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080
```
The VPN connects fine and the health checks seem fine as well - I've also tried to exclude my IP through the `PROTONVPN_EXCLUDE_CIDRS` env. variable.
The Web Interface can connect for a second before the VPN gets connected.
Both containers have the same IP when trying to `curl ifconfig.io` - obviously getting a VPN IP.
I'm trying to access the Web Interface from outside the LAN and have opened the ports and have tested that it works without the ProtonVPN Docker.
I must disclose that I'm a complete "newb" to Docker and only recently discovered it, so I'm in no way an expert.

**Comment by tprasadtp** [comment]
Try adding your docker network CIDRs to exclude list.

**Comment by oatmealm** [comment]
The CIDR is not the issue. I have a similar setup with the CIDR set correctly to my private local network, as required, yet I still see the same problem and I can't connect to the internet via the container.

**Comment by tprasadtp** [comment]
@oatmealm Could you please check it with 4.x release? I think it was created by enabling killswitch in the config file.
```ini
killswitch = 1
```
and because protonvpn-cli uses `iptables -P INPUT DROP` when killswitch=1, this resulted in dropped dropped traffic and hence timeout. on ports :grin: :facepalm: :facepalm: 

Try this docker-compose config and let me know if it still results in timeouts

```yaml
version: '3.4'
services:
  protonvpn:
    container_name: protonvpn
    environment:
      PROTONVPN_COUNTRY: NL
      PROTONVPN_USERNAME: ${PROTONVPN_USERNAME}
      PROTONVPN_PASSWORD: ${PROTONVPN_PASSWORD}
      PROTONVPN_TIER: ${PROTONVPN_TIER:-0}
    image: ghcr.io/tprasadtp/protonvpn:latest
    restart: unless-stopped
    networks:
      - internet
      - proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - 8000
  pyload:
    depends_on:
      - protonvpn
    container_name: pyload
    environment:
      TZ: "Europe/Berlin"
      PGID: "1000"
      PUID: "1000"
    image: linuxserver/pyload:latest
    restart: unless-stopped
    userns_mode: host
    network_mode: service:protonvpn
    volumes:
      - config:/config
      - ./downloads/:/downloads/:rw
volumes:
  config:
networks:
  internet:
  proxy:
    internal: true
```
Be sure to pull the latest image and export your credentials as env variables first.

**Comment by oatmealm** [comment]
Will get to it ASAP. Thanks!

**Comment by maclarel** [comment]
I'm hitting this as well, with or without kill switch usage. I'll get a brief blip of connectivity to whatever service is being exposed (qBittorrent in my case) and once the VPN connections I get timeouts. 

If I disconnect the VPN from in the container, it is immediately available again.

I believe, to some extent, this may be unavoidable as the routes pushed by the VPN only allow outbound traffic over the VPN interface:

```
# ip route
0.0.0.0/1 via 10.20.0.1 dev proton0
default via 192.168.240.1 dev eth0
10.20.0.0/16 dev proton0 proto kernel scope link src 10.20.0.3
128.0.0.0/1 via 10.20.0.1 dev proton0
172.20.0.0/16 dev eth1 proto kernel scope link src 172.20.0.2
185.159.158.58 via 192.168.240.1 dev eth0
192.168.240.0/20 dev eth0 proto kernel scope link src 192.168.240.2
```

vs the following when the VPN is not connected

```
# ip route
default via 192.168.240.1 dev eth0
172.20.0.0/16 dev eth1 proto kernel scope link src 172.20.0.2
192.168.240.0/20 dev eth0 proto kernel scope link src 192.168.240.2
```

Any attempts *internally to the protonvpn container* on the exposed port (8080 in this case) work fine due to `192.168.240.0/20 dev eth0 proto kernel scope link src 192.168.240.2` but any connection attempt from outside of the container will fail as soon as the VPN connection due to the appended `0.0.0.0/1 via 10.20.0.1 dev proton0` grabbing all traffic prior to the default route.

*HOWEVER* if I append a new route specifically for my LAN traffic (`10.0.1.0/24` in my case) I'm again able to access the exposed service. In my case, this consists of running `ip route append 10.0.1.0/24 via 192.168.240.1 dev eth0`. Unfortunately, I'm not aware of a way to add this in a persist method short of forking this project and adding it to my own dockerfile, which is less than ideal...

Thoughts @tprasadtp ?

**Comment by tprasadtp** [comment]
Hey @maclarel try this and let me know if you still have timeout issues. 

## Debugging with default compose file

1. Stop and delete existing containers named `protonvpn` and `pyload` (if any).
1. Please export credentials as environment variables `PROTONVPN_USERNAME` and `PROTONVPN_PASSWORD` and optionally `PROTONVPN_TIER`.
This depends on your shell. Please consult your shell's manpage/docs for how to export environment variables.
1. Get your debugging [compose file][] and create a temporary folder required to save pyload downloads.
    ```bash
    curl -sSfLO https://raw.githubusercontent.com/tprasadtp/protonvpn-docker/master/k8s/docker-compose.yml
    mkdir -p ./downloads
    ```
1. Try to run downloaded [compose file][]
    ```bash
    docker-compose up
    ```
1. We intentionally do not expose in this config, `pyload` to outside world. depending on your system and runtime constraints IP address of your container will vary. To obtain IP address/URL of your `pyload` service,run
    ```bash
    docker inspect --format='{{range .NetworkSettings.Networks}}{{printf "http://%s:8000\\n" .IPAddress}}{{end}}' protonvpn
    ```
1. Visit the link in your browser.
1. If for some reason you get timeout errors, please specify output of following when running inside protonvpn container via `docker exec -it protonvpn bash`.
    - `ip r`
    - `curl -sSfL ipinfo.io`

## Runtime configuration

1. I am running with following configuration
    - Version of `protonvpn-docker` :
    - Host architecture:

1. I have following connected containers:
    - Image:
    - Version(Optional):

Also, can you complete the following template? You can copy the contents below in your response.


## Docker configuration

- [ ] Using custom runtime
- [ ] Using user namespaces
- [ ] Using rootless containers
- [ ] Using with podman
- [ ] Using with k8s/Kubernetes/Openshift

## Redacted PII & Credential validation

- [ ] I have redacted any personally identifying information like public IP address, hostnames, usernames and passwords if they are present in the output.
- [x] I have verfied that my VPN credentials are valid.

**Comment by maclarel** [comment]
Hey @tprasadtp thanks for getting back to me so quickly here! 🎉 

I think I have this all figured out at this point as outlined at the end of my post above. With that said, I'd be happy to test some changes if you think there's an easier way... It's not immediately apparent from the linked docker-compose.yml what would be changing here - could you let me know what to look for?

**Comment by tprasadtp** [comment]
@maclarel P The compose file specified runs `pyload` which is plain, boring and simple. Thus it acts like a common denominator in debugging and makes easier for everyone to reproduce the issue as everyone may not be comfortable running a P2P image.

That being said original author of this issue mentioned that exclude cidrs did not work for them. However it was before 4.x releases. Please let me know if your setup is working as you intended.

**Comment by maclarel** [comment]
> That being said original author of this issue mentioned that exclude cidrs did not work for them. However it was before 4.x releases. Please let me know if your setup is working as you intended.

Aha! Gotcha, yeah `PROTONVPN_EXCLUDE_CIDRS` is working perfectly for me with the `latest` container. As it turns out, forcing qBitorrent to bind to the `proton0` network interface also gives it a software level "kill switch" so it gets around the issues with the ProtonVPN implementation since that interface vanishes entirely if it's not connected!

I wonder if the OP here wasn't formatting the `PROTONVPN_EXCLUDE_CIDRS` values properly? I know the init scripts do some validation on those values... maybe they were getting dumped?

**Comment by tprasadtp** [comment]
Perfect!
@maclarel 
The reason I did not include `proton0` interface in the docs is because
1. Not all software provide a way to bind to an interface. For me, better way would be to handle it in the container init phase. In k8s you can achieve it with init containers, though I did not include it in the docs because It involves a special init container which was very specific to my setup. 
2. We used to match release tags with upstream and they would rename the interface between patch releases. Now that is 
no longer the case, and we are pinning out upstream release, I think it can be included. (Perfect  for a PR :wink: :wink: )

To answer your second question, I have not received feedback from the original author of this issue. They were using pre 3.1 release which indeed had this issue. 

I will leave this issue pinned as it is helpful for other uses who might have the similar issue.

**Comment by oatmealm** [comment]
Hi there! Sorry for the long delay... I can confirm I have tested it and it seems to work with tinyproxy.
Thanks!

**Comment by lhoupert** [comment]
> Hey @maclarel try this and let me know if you still have timeout issues.
> ## Debugging with default compose file
> 
>     1. Stop and delete existing containers named `protonvpn` and `pyload` (if any).
> 
>     2. Please export credentials as environment variables `PROTONVPN_USERNAME` and `PROTONVPN_PASSWORD` and optionally `PROTONVPN_TIER`.
>        This depends on your shell. Please consult your shell's manpage/docs for how to export environment variables.
> 
>     3. Get your debugging [compose file][] and create a temporary folder required to save pyload downloads.
>        ```shell
>        curl -sSfLO https://raw.githubusercontent.com/tprasadtp/protonvpn-docker/master/k8s/docker-compose.yml
>        mkdir -p ./downloads
>        ```
> 
>     4. Try to run downloaded [compose file][]
>        ```shell
>        docker-compose up
>        ```
> 
>     5. We intentionally do not expose in this config, `pyload` to outside world. depending on your system and runtime constraints IP address of your container will vary. To obtain IP address/URL of your `pyload` service,run
>        ```shell
>        docker inspect --format='{{range .NetworkSettings.Networks}}{{printf "http://%s:8000\\n" .IPAddress}}{{end}}' protonvpn
>        ```
> 
>     6. Visit the link in your browser.
> 
>     7. If for some reason you get timeout errors, please specify output of following when running inside protonvpn container via `docker exec -it protonvpn bash`.
>        
>        * `ip r`
>        * `curl -sSfL ipinfo.io`
> 
> 
> ## Runtime configuration
> 
>     1. I am running with following configuration
>        
>        * Version of `protonvpn-docker` :
>        * Host architecture:
> 
>     2. I have following connected containers:
>        
>        * Image:
>        * Version(Optional):
> 
> 
> Also, can you complete the following template? You can copy the contents below in your response.
> ## Docker configuration
> 
>     * [ ]  Using custom runtime
> 
>     * [ ]  Using user namespaces
> 
>     * [ ]  Using rootless containers
> 
>     * [ ]  Using with podman
> 
>     * [ ]  Using with k8s/Kubernetes/Openshift
> 
> 
> ## Redacted PII & Credential validation
> 
>     * [ ]  I have redacted any personally identifying information like public IP address, hostnames, usernames and passwords if they are present in the output.
> 
>     * [x]  I have verfied that my VPN credentials are valid.

Hi all, I encountered the same problem of timeout when I want to access the webgui of pyload through the port 8000.

I tried several things but nothing worked.... I managed to access the port 8000 when running pyload without protonvpn.

I follow what you said, the curl command didnt work so I use the docker-compose.yml from the docs website:

```yml
version: '3.4'
services:
  protonvpn:
    container_name: protonvpn
    environment:
      # Credentials
      PROTONVPN_USERNAME: ${PROTONVPN_USERNAME}
      PROTONVPN_PASSWORD: ${PROTONVPN_PASSWORD}
      # Override these where applicable
      PROTONVPN_SERVER: ${PROTONVPN_SERVER}
      PROTONVPN_TIER: ${PROTONVPN_TIER}
    # Always use semver tags, avoid using tag latest!
    image: ghcr.io/tprasadtp/protonvpn:latest
    restart: unless-stopped
    networks:
      - internet
      - proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # Expose pyload container's port here!
    expose:
      - 8000
  # Your app using the VPN
  # Here we use pyload as an example
  pyload:
    depends_on:
      - protonvpn
    container_name: pyload
    environment:
      TZ: "Europe/Berlin"
      PGID: "1000"
      PUID: "1000"
    image: linuxserver/pyload:latest
    restart: unless-stopped
    userns_mode: host
    # Do not apply any networking configs
    # on this container!
    # All networking labels and settings should be defined
    # on the vpn container.
    network_mode: service:protonvpn
    volumes:
      - config:/config
      - ./downloads/:/downloads/:rw
volumes:
  config:
networks:
  internet:
  proxy:
    internal: true

``` 

Both containers are running fine.

The command `test sudo docker inspect --format='{{range .NetworkSettings.Networks}}{{printf "http://%s:8000\\n" .IPAddress}}{{end}}' protonvpn` is returning me `http://192.168.112.2:8000\nhttp://192.168.128.2:8000\n`

I also have timeout erros for both address.

And the command `ip r` is giving me :

```
root@edf0187cd094:/# ip r
0.0.0.0/1 via 10.19.0.1 dev proton0 
default via 192.168.112.1 dev eth0 
10.19.0.0/16 dev proton0 proto kernel scope link src 10.19.0.10 
89.44.201.162 via 192.168.112.1 dev eth0 
128.0.0.0/1 via 10.19.0.1 dev proton0 
169.254.169.254 via 192.168.112.1 dev eth0 
169.254.170.2 via 192.168.112.1 dev eth0 
192.168.112.0/20 dev eth0 proto kernel scope link src 192.168.112.2 
192.168.128.0/20 dev eth1 proto kernel scope link src 192.168.128.2 
root@edf0187cd094:/# curl -sSfL ipinfo.io
{
  "ip": "89.44.201.166",
  "city": "Manchester",
  "region": "England",
  "country": "GB",
  "loc": "53.4809,-2.2374",
  "org": "AS9009 M247 Ltd",
  "postal": "M61",
  "timezone": "Europe/London",
  "readme": "https://ipinfo.io/missingauth"
}root@edf0187cd094:/# 

```

Any idea of what I am missing?
