### ISSUE TITLE
[QUESTION]: Could not resolve host: protonwire-api.vercel.app

### ISSUE THREAD

**Issue by Anthony-Eid** [tprasadtp/protonvpn-docker#300]
### Version

2.3/protonwire:latest 

### Support Request

Hi guys,

I'm trying to use this container to connect to proton vpn but keep running into "Could not resolve host: proton-api.vercel.app error.

I've check that the docker container is getting my private-key correctly, and that I could access https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net  via my web browser. 

Here's my docker compose file 

```yml
version: '2.3'
services:
  protonwire:
    container_name: protonwire
    # Use semver tags or sha256 hashes of manifests.
    # using latest tag can lead to issues when used with
    # automatic image updaters like watchtower/podman.
    image: ghcr.io/tprasadtp/protonwire:latest
    init: true
    restart: unless-stopped
    environment:
      # Quote this value as server name can contain '#'.
      PROTONVPN_SERVER: "node-nl-96.protonvpn.net"  # NL-FREE#100070
      # Set this to 1 to show debug logs for issue forms.
      DEBUG: "1"
      # Set this to 0 to disable kill-switch.
      KILL_SWITCH: "0"
    # NET_ADMIN capability is mandatory!
    cap_add:
      - NET_ADMIN
    # sysctl net.ipv4.conf.all.rp_filter is mandatory!
    # net.ipv6.conf.all.disable_ipv6 disables IPv6 as protonVPN does not support IPv6.
    # 'net.*' sysctls are not required on application containers,
    # as they share network stack with protonwire container.
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - type: bind
        source: private-key
        target: /etc/protonwire/private-key
        read_only: true
    ports:
      - 8000:80

  caddy_proxy:
    image: caddy:latest
    network_mode: service:protonwire
    command: |
      caddy reverse-proxy \
      --change-host-header \
      --from :80 \
      --to https://ip.me:443

```

Here are the error messages via docker logs protonwire. The main things that sticks out to me are `Server info file is missing - /tmp/protonwire.server.json `, and that DNS is having issues being resolved. I've tried different proton ip addresses, and googling this but couldn't find out. I also checked my Pi hole to see if the DNS was being blocked, and it wasn't.

Does anyone have any suggestions for how I could fix this? Could it be something with the docker container not having the correct firewall settings? I'm on Fedora linux, which has SElinux enabled. 

- [DEBUG   ] PROTONVPN_SERVER                    : node-nl-96.protonvpn.net 
- [DEBUG   ] IPCHECK_URL                         : https://protonwire-api.vercel.app/v1/client/ip 
- [DEBUG   ] METADATA_URL                        : https://protonwire-api.vercel.app/v1/server 
- [DEBUG   ] Running as container USER=root 
- [DEBUG   ] Checking requirements 
- [DEBUG   ] Using /etc/resolv.conf for DNS (systemd is not available) 
- [DEBUG   ] RUNTIME_DIRECTORY                   : NA 
- [DEBUG   ] XDG_RUNTIME_DIR                     : NA 
- [DEBUG   ] __PROTONWIRE_SRV_INFO_FILE          : /tmp/protonwire.server.json 
- [DEBUG   ] __PROTONWIRE_HCR                    : /tmp/protonwire.hc.response 
- [DEBUG   ] WATCHDOG_USEC is not set or invalid 
- [DEBUG   ] Checking if IP on other interface is reserved - 127.0.0.1 
- [DEBUG   ] Checking if IP on other interface is reserved - 172.24.0.2 
- [NOTICE  ] Skipped validating default IPCHECK_URL 
- [DEBUG   ] Can use CAP_NET_ADMIN capability 
- [DEBUG   ] IPCHECK_THRESHOLD                   : NA 
- [DEBUG   ] IPCHECK_INTERVAL                    : NA 
- [DEBUG   ] Server info file is missing - /tmp/protonwire.server.json 
- [INFO    ] Refresing server metadata (for node-nl-96.protonvpn.net) 
- [DEBUG   ] API - https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net 
- [TRACE   ] (curl) % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
- [TRACE   ] (curl) Dload  Upload   Total   Spent    Left  Speed 
-   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: protonwire-api.vercel.app 
- [TRACE   ] (curl) * Closing connection 
- [TRACE   ] (curl) curl: (6) Could not resolve host: protonwire-api.vercel.app 
- [ERROR   ] Failed to refresh ProtonVPN server metadata (failed to resolve domain) 
- [ERROR   ] Retrying after 2 seconds (1/3) 
- [DEBUG   ] Server info file is missing - /tmp/protonwire.server.json 
- [INFO    ] Refresing server metadata (for node-nl-96.protonvpn.net) 
- [DEBUG   ] API - https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net 
- [TRACE   ] (curl) % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
- [TRACE   ] (curl) Dload  Upload   Total   Spent    Left  Speed 
-   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: protonwire-api.vercel.app 
- [TRACE   ] (curl) * Closing connection 
- [TRACE   ] (curl) curl: (6) Could not resolve host: protonwire-api.vercel.app 
- [ERROR   ] Failed to refresh ProtonVPN server metadata (failed to resolve domain) 
- [ERROR   ] Retrying after 4 seconds (2/3) 
- [DEBUG   ] Server info file is missing - /tmp/protonwire.server.json 
- [INFO    ] Refresing server metadata (for node-nl-96.protonvpn.net) 
- [DEBUG   ] API - https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net 
- [TRACE   ] (curl) % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
- [TRACE   ] (curl) Dload  Upload   Total   Spent    Left  Speed 
-   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: protonwire-api.vercel.app 
- [TRACE   ] (curl) * Closing connection 
- [TRACE   ] (curl) curl: (6) Could not resolve host: protonwire-api.vercel.app 
- [ERROR   ] Failed to refresh ProtonVPN server metadata (failed to resolve domain) 
- [DEBUG   ] metadata_fetch_tries=3 
- [DEBUG   ] metadata_fetch_max_tries=3 
- [ERROR   ] Failed to fetch server metadata after 3 tries! 
- [ERROR   ] Please check your internet connection and try again! 
- [ERROR   ] If you have killswitch enabled please disable it and try again! 
- [ERROR   ] Failed to connect to node-nl-96.protonvpn.net 
- [DEBUG   ] Wireguard interface for protonwire is not present. 
- [DEBUG   ] PROTONVPN_SERVER                    : node-nl-96.protonvpn.net 
- [DEBUG   ] IPCHECK_URL                         : https://protonwire-api.vercel.app/v1/client/ip 
- [DEBUG   ] METADATA_URL                        : https://protonwire-api.vercel.app/v1/server 
- [DEBUG   ] Running as container USER=root 
- [DEBUG   ] Checking requirements 
- [DEBUG   ] Using /etc/resolv.conf for DNS (systemd is not available) 
- [DEBUG   ] RUNTIME_DIRECTORY                   : NA 
- [DEBUG   ] XDG_RUNTIME_DIR                     : NA 
- [DEBUG   ] __PROTONWIRE_SRV_INFO_FILE          : /tmp/protonwire.server.json 
- [DEBUG   ] __PROTONWIRE_HCR                    : /tmp/protonwire.hc.response 
- [DEBUG   ] WATCHDOG_USEC is not set or invalid 
- [DEBUG   ] Checking if IP on other interface is reserved - 127.0.0.1 
- [DEBUG   ] Checking if IP on other interface is reserved - 172.24.0.2 
- [NOTICE  ] Skipped validating default IPCHECK_URL 
- [DEBUG   ] Can use CAP_NET_ADMIN capability 
- [DEBUG   ] IPCHECK_THRESHOLD                   : NA 
- [DEBUG   ] IPCHECK_INTERVAL                    : NA 
- [DEBUG   ] Server info file is missing - /tmp/protonwire.server.json 
- [INFO    ] Refresing server metadata (for node-nl-96.protonvpn.net) 
- [DEBUG   ] API - https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net 
- [TRACE   ] (curl) % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
- [TRACE   ] (curl) Dload  Upload   Total   Spent    Left  Speed 
-   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: protonwire-api.vercel.app 
- [TRACE   ] (curl) * Closing connection 
- [TRACE   ] (curl) curl: (6) Could not resolve host: protonwire-api.vercel.app 
- [ERROR   ] Failed to refresh ProtonVPN server metadata (failed to resolve domain) 
- [ERROR   ] Retrying after 2 seconds (1/3) 
- [DEBUG   ] Server info file is missing - /tmp/protonwire.server.json 
- [INFO    ] Refresing server metadata (for node-nl-96.protonvpn.net) 
- [DEBUG   ] API - https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net 
- [TRACE   ] (curl) % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
- [TRACE   ] (curl) Dload  Upload   Total   Spent    Left  Speed 
-   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: protonwire-api.vercel.app 
- [TRACE   ] (curl) * Closing connection 
- [TRACE   ] (curl) curl: (6) Could not resolve host: protonwire-api.vercel.app 
- [ERROR   ] Failed to refresh ProtonVPN server metadata (failed to resolve domain) 
- [ERROR   ] Retrying after 4 seconds (2/3) 
- [DEBUG   ] Server info file is missing - /tmp/protonwire.server.json 
- [INFO    ] Refresing server metadata (for node-nl-96.protonvpn.net) 
- [DEBUG   ] API - https://protonwire-api.vercel.app/v1/server/node-nl-96.protonvpn.net 
- [TRACE   ] (curl) % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
- [TRACE   ] (curl) Dload  Upload   Total   Spent    Left  Speed 
-   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: protonwire-api.vercel.app 
- [TRACE   ] (curl) * Closing connection 
- [TRACE   ] (curl) curl: (6) Could not resolve host: protonwire-api.vercel.app 
- [ERROR   ] Failed to refresh ProtonVPN server metadata (failed to resolve domain) 
- [DEBUG   ] metadata_fetch_tries=3 
- [DEBUG   ] metadata_fetch_max_tries=3 
- [ERROR   ] Failed to fetch server metadata after 3 tries! 
- [ERROR   ] Please check your internet connection and try again! 
- [ERROR   ] If you have killswitch enabled please disable it and try again!

### Code of Conduct & PII Redaction

- [X] I have verified that this feature request is not a duplicate and is not not addressed by the [FAQ](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/faq.md) and [Troubleshooting](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/help.md).
- [X] This is not a bug report or feature request.
- [X] I agree to follow this project's Code of Conduct.
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.
