### ISSUE TITLE
[BUG] -  failed to create task for container

### ISSUE THREAD

**Issue by Sispheor** [tprasadtp/protonvpn-docker#312]
### Version

7.5.2

### Credential and Server Validation

- [X] I have verified that the servers I am trying to connect to are available under my plan.
- [X] I have verified that my generated Wireguard private keys are valid and have required features (Netshield Ad-blocker, VPN accelerator etc) are enabled.
- [X] I am using a valid server name (either fully qualified DNS name like `nl-free-127.protonvpn.net` or server IP) as mentioned in the docs.

### System Architecture

x86_64

### Kernel Version

5.10.0-29-amd64

### Running on a NAS?

Yes

### Runtime

docker

### Version of Runtime

```
docker --version
Docker version 26.1.3, build b72abbb

docker compose version
Docker Compose version v2.27.0

```

### My configuration

My config
```
version: '3.7'

services:
  protonvpn:
    container_name: protonvpn
    #image: ghcr.io/tprasadtp/protonwire:7.3.0-beta3 # I was on this image, no prob
    image: ghcr.io/tprasadtp/protonwire:7.5.2  # moving to the last stable 
    command: "sh /config/protonvpn-init.sh" 
    restart: always
    environment:
      WIREGUARD_PRIVATE_KEY: secret
      PROTONVPN_SERVER: 146.70.86.114
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - ./protonvpn-port:/config/protonvpn-port
      - ./protonvpn-init.sh:/config/protonvpn-init.sh
      - /dev/net/tun:/dev/net/tun
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8112:8112"
      - "58846:58846"
```

The init script:
```
/usr/bin/protonwire connect & # seems to stop here

echo "sleep 10 seconds"
sleep 10 # Arbitrary 10s sleep to wait for the VPN to connect, probs a better way to do it but wanted a quick win

echo get random UDP port
natpmpc -a 1 0 udp 60 -g 10.2.0.1 # Ask for UDP port forwarding
natpmpc -a 1 0 tcp 60 -g 10.2.0.1 | grep -oP 'public\ port\ \K\w+' > /config/protonvpn-port # Ask for TCP port forwarding and extract the port number to file

echo "Port written to protonvpn-port file"
cat /config/protonvpn-port

echo "Keep the port forwarding alive"
while true ; do date ; natpmpc -a 1 0 udp 60 -g 10.2.0.1 && natpmpc -a 1 0 tcp 60 -g 10.2.0.1 || { echo -e "ERROR with natpmpc command \a" ; break ; } ; sleep 50 ; done

```

### Whitelisting API endpoints

I am not using ad-blocking DNS server or gateway

### Troubleshooting & Runtime

- [X] Wireguard is supported by my kernel
- [X] I have read [FAQ](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/faq.md) and [Troubleshooting](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/help.md).
- [X] I am using latest stable version

### Container/Pod/systemd log output with DEBUG=1 or `--debug` flag

```log
Here is the last output:

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/25720/ns/net: no such file or directory: unknown
```

Complete output (protonwire client is showing the cli help like if I had an error in the command):
```
protonvpn  | 
protonvpn  | ProtonVPN WireGuard Client
protonvpn  | 
protonvpn  | Usage: protonwire [OPTIONS...]
protonvpn  | or: protonwire [OPTIONS...] c|connect [SERVER]
protonvpn  | or: protonwire [OPTIONS...] d|disconnect
protonvpn  | or: protonwire [OPTIONS...] check
protonvpn  | or: protonwire [OPTIONS...] disable-killswitch
protonvpn  | or: protonwire [OPTIONS...] server-info [SERVER]
protonvpn  | 
protonvpn  | Options:
protonvpn  |   -k, --private-key FILE|KEY    Wireguard private key or
protonvpn  |                                 file containing private key
protonvpn  |       --service                 Run as service
protonvpn  |       --service-status-file     Use status file created by --service
protonvpn  |                                 for healthchecks. Only valid when both process
protonvpn  |                                 are running within the same container.
protonvpn  |       --metadata-url URL        Server metadata endpoint URL
protonvpn  |       --check-interval INT      IP check interval in seconds (default 60)
protonvpn  |       --check-url URL           IP check endpoint URL
protonvpn  |       --skip-dns-config         Skip configuring DNS.
protonvpn  |                                 (Useful for Kubernetes and Consul)
protonvpn  |       --kill-switch             Enable killswitch (Experimental)
protonvpn  |       --p2p                     Verify if specified server supports P2P
protonvpn  |       --streaming               Verify if specified server supports streaming
protonvpn  |       --tor                     Verify if specified server supports Tor
protonvpn  |       --secure-core             Verify if specified server supports secure core
protonvpn  |   -q, --quiet                   Show only errors
protonvpn  |   -v, --verbose                 Show debug logs
protonvpn  |   -h, --help                    Display this help and exit
protonvpn  |       --version                 Display version and exit
protonvpn  | 
protonvpn  | Examples:
protonvpn  |   protonwire connect nl-1       Connect to server nl-1
protonvpn  |   protonwire d --kill-switch    Disconnect from current server and disable kill-switch
protonvpn  |   protonwire verify [SERVER]    Check if connected to a server
protonvpn  | 
protonvpn  | Files:
protonvpn  |   /etc/protonwire/private-key   WireGuard private key
protonvpn  | 
protonvpn  | Environment:
protonvpn  |   WIREGUARD_PRIVATE_KEY         WireGuard private key or file
protonvpn  |   PROTONVPN_SERVER              ProtonVPN server
protonvpn  |   IPCHECK_INTERVAL              Custom IP check interval in seconds (default 60)
protonvpn  |   IPCHECK_URL                   IP check endpoint URL (must be https://)
protonvpn  |   SKIP_DNS_CONFIG               Set to '1' to skip configuring DNS
protonvpn  |   KILL_SWITCH                   Set to '1' to enable killswitch (Experimental)
protonvpn  |   DEBUG                         Set to '1' to enable debug logs
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/25720/ns/net: no such file or directory: unknown
```
```


### Any additional info

Thanks for this project ! 😊

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct.
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.
