### ISSUE TITLE
[QUESTION]: Access port from other machine on local network

### ISSUE THREAD

**Issue by bjrb20** [tprasadtp/protonvpn-docker#325]
### Version

linuxserver/qbittorrent@sha256:fdbd674da0d9e676b37e7c5d3fa8189e5ec0b7d507549d80d9bc46e95db7875a

### Support Request

I have the configuration running on a headless pi 4 successfully:

```
services:
  protonwire:
    image: ghcr.io/tprasadtp/protonwire:latest
    container_name: protonwire
    cap_add:
      - NET_ADMIN
    environment:
      PROTONVPN_SERVER: 'REDACTED' # Replace with your desired server
      WIREGUARD_PRIVATE_KEY: 'REDACTED' # Replace with your WireGuard private key
      KILL_SWITCH: '1' # Enable kill switch
    dns:
      - 1.1.1.1
      - 8.8.8.8
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
    ports:
      - '8090:8090'
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - protonwire
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090
      - UMASK_SET=022
      - TZ=Etc/UTC
    volumes:
      - /portainer/Files/AppData/Config/qBittorrent:/config
      - /usr/downloads:/downloads
    network_mode: 'service:protonwire'
    restart: unless-stopped
```

If I ssh into the pi and run `curl http://localhost:8090` I get the html response of the login page as expected but if I try to access it from another machine using the local ip of the pi `curl http://x.x.x.x:8090/` I get `curl: (28) Failed to connect to x.x.x.x port 8090 after 133430 ms: Couldn't connect to server`

Other docker services running on the pi are accessible over the local network with no issues so I assume this is due the the vpn. Can anyone point me in the right direction to resolve this?

### Code of Conduct & PII Redaction

- [X] I have verified that this feature request is not a duplicate and is not not addressed by the [FAQ](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/faq.md) and [Troubleshooting](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/help.md).
- [X] This is not a bug report or feature request.
- [X] I agree to follow this project's Code of Conduct.
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by hpirila** [comment]
Hi,

I tried very similar docker compose file and it works fine, I can access web port 8080 from an other PC browser. Also I can confirm VPN is used in torrent traffic. The compose file I used is like this:

```
services:
  protonvpn:
    image: ghcr.io/tprasadtp/protonwire:latest
    container_name: protonvpn
    cap_add:
      - NET_ADMIN
    environment:
      PROTONVPN_SERVER: "111.222.111.222"
      KILL_SWITCH: '1' 
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - configvpn:/etc/protonwire
    ports:
      - 8080:8080
    restart: unless-stopped

  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent
    depends_on:
      - protonvpn
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
    volumes:
      - configqbt:/config
      - /home/zzzzz/downloads:/downloads
    network_mode: 'service:protonvpn'
    restart: unless-stopped

volumes:
  configvpn:
  configqbt:
  downloads:
```

Additional kill switch tip: 

In qbittorrent Options - Advanced - Optional IP address to bind to: `protonwire0`
