### ISSUE TITLE
Cannot connect to random server

### ISSUE THREAD

**Issue by Glogo** [tprasadtp/protonvpn-docker#36]
When I'm setting `PROTONVPN_SERVER` to value `RANDOM` I'm unable to connect and getting errors. I'm not setting `PROTONVPN_COUNTRY`

Logs:
```
protonvpn          | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
protonvpn          | [s6-init] ensuring user provided files have correct perms...exited 0.
protonvpn          | [fix-attrs.d] applying ownership & permissions fixes...
protonvpn          | [fix-attrs.d] done.
protonvpn          | [cont-init.d] executing container initialization scripts...
protonvpn          | [cont-init.d] 70-vpn-setup: executing...
protonvpn          | [VPN-Config-Setup] Using Server RANDOM
protonvpn          | [VPN-Config-Setup] Plus Plan
protonvpn          | [VPN-Config-Setup] TCP
protonvpn          | [VPN-Config-Split] Validating CIDRs
protonvpn          | [VPN-Config-Split] CIDR 169.254.169.254/32 is valid
protonvpn          | [VPN-Config-Split] CIDR 169.254.170.2/32 is valid
protonvpn          | [VPN-Config-DNS  ] Enabling DNS leak protection.
protonvpn          | [VPN-Config-Split] Following CIDRs will be excluded from VPN 169.254.169.254/32 169.254.170.2/32
protonvpn          | [Path Init       ] Creating folders
protonvpn          | [Path Init       ] Permissions
protonvpn          | [VPN-Config-Setup] Getting Server List
protonvpn          | [VPN-Config-Setup] Writing config file
protonvpn          | [VPN-Config-Setup] Writing Split Tunnel Config file
protonvpn          | [VPN-Config-Setup] Writing credentials file
protonvpn          | [VPN-Config-Setup] Restrict credentials file
protonvpn          | [cont-init.d] 70-vpn-setup: exited 0.
protonvpn          | [cont-init.d] done.
protonvpn          | [services.d] starting services
protonvpn          | [services.d] done.
protonvpn          | [Service - INIT] Daemon check interval is set to #60
protonvpn          | [Service - INIT] Reconnect treshold is #3
protonvpn          | [Service - INIT] checking orphaned openvpn process
protonvpn          | [Service - INIT] This appears to be a fresh start!
protonvpn          | [Service - CONN] Using Server RANDOM
protonvpn          | [!] 'RANDOM' is not a valid servername
protonvpn          | [!] Please enter a valid servername
protonvpn          | [Service - INIT] PROTONVPN_SVC_DISCONNECTING: 0
protonvpn          | [Service - CHCK] Error!! There is no OpenVPN Process!!
protonvpn          | [Service - RCON] Attempting...
protonvpn          | [!] Couldn't find a previous connection
protonvpn          | [!] Please connect normally first
protonvpn          | [Service - RCON] Failure!
protonvpn          | [Service - RCON] Trying with a fresh connection!
protonvpn          | [Service - CONN] Using Server RANDOM
protonvpn          | [!] 'RANDOM' is not a valid servername
protonvpn          | [!] Please enter a valid servername
```

My docker-compose file:
```
version: '3'
services:
  protonvpn:
    image: ghcr.io/tprasadtp/protonvpn:latest # also tried 4.1.2 with the same effect
    container_name: protonvpn
    restart: unless-stopped
    environment:
      # Credentials
      PROTONVPN_USERNAME: ...
      PROTONVPN_PASSWORD: ...
      PROTONVPN_SERVER: RANDOM
      # PROTONVPN_COUNTRY: 'NL' # works when I use this setting instead of server
      PROTONVPN_TIER: 2
    networks:
      - internet
      - proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  ... service with my app

networks:
  internet:
  proxy:
    internal: true
```
