### ISSUE TITLE
curl: (28) Timeout was reached on 

### ISSUE THREAD

**Issue by LtPinback** [tprasadtp/protonvpn-docker#42]
Hi!

I have been trying to setup this container and it fails on requesting the vpn servers list json.
I suspect the DNS is not working. 

I did try with/without:
DNS leak protection
specifying the DNS
and even using network_mode; bridge to inherit host DNS
but nothing seem to work.

What am I doing wrong?

docker-compose-yml
```
version: '3.4'

services:
  protonvpn:
    container_name: protonvpn
    environment:
      # Credentials
      PROTONVPN_USERNAME: <REDACTED>
      PROTONVPN_PASSWORD: <REDACTED>
      # Override these where applicable
      PROTONVPN_COUNTRY: NL
      PROTONVPN_TIER: 2
      PROTONVPN_DNS_LEAK_PROTECT: 0
      DNS: 1.1.1.1
    image: ghcr.io/tprasadtp/protonvpn:latest
    restart: unless-stopped
    networks:
      - internet
      - proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - 8000

volumes:
  config:
networks:
  internet:
  proxy:
    internal: true
```

Log file
```
Recreating protonvpn ... done
Attaching to protonvpn
protonvpn    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
protonvpn    | [s6-init] ensuring user provided files have correct perms...exited 0.
protonvpn    | [fix-attrs.d] applying ownership & permissions fixes...
protonvpn    | [fix-attrs.d] done.
protonvpn    | [cont-init.d] executing container initialization scripts...
protonvpn    | [cont-init.d] 70-vpn-setup: executing...
protonvpn    | [VPN-Config-Setup] Using Fastest Server from NL
protonvpn    | [VPN-Config-Setup] Plus Plan
protonvpn    | [VPN-Config-Setup] UDP
protonvpn    | [VPN-Config-Split] Validating CIDRs
protonvpn    | [VPN-Config-Split] CIDR 169.254.169.254/32 is valid
protonvpn    | [VPN-Config-Split] CIDR 169.254.170.2/32 is valid
protonvpn    | [VPN-Config-DNS  ] Disabling DNS leak protection!!
protonvpn    | [VPN-Config-Split] Following CIDRs will be excluded from VPN 169.254.169.254/32 169.254.170.2/32
protonvpn    | [Path Init       ] Creating folders
protonvpn    | [Path Init       ] Permissions
protonvpn    | [VPN-Config-Setup] Getting Server List
protonvpn    | curl: (28) Timeout was reached
protonvpn    | [cont-init.d] 70-vpn-setup: exited 28.
protonvpn    | [cont-finish.d] executing container finish scripts...
protonvpn    | [cont-finish.d] done.
protonvpn    | [s6-finish] waiting for services.
protonvpn    | [s6-finish] sending all processes the TERM signal.
```
